.Dd November 16, 2023
.Dt JDICT 1
.
.Sh NAME
.Nm jdict
.Nd search through japanese dictionaries
.
.Sh SYNOPSIS
.Nm
.Op Fl d Ar dictionary
.Op Fl F Ar FS
.Op Fl i
.Ar term ...
.
.Sh DESCRIPTION
The
.Nm
utility searches through dictionaries formatted in the yomidict
format for
.Ar term ...
and outputs any found definitions to stdout.
.Pp
The following options are supported:
.
.Bl -tag -width Ds
.It Fl d Ar dictionary
limit search to the specified
.Ar dictionary .
.It Fl F Ar FS
use
.Ar FS
for output field separation.
.It Fl i
run the program in interactive mode. FS will be set to "\\n".
.El
.
.Sh CUSTOMIZATION
.Nm
is customized by modifying config.h and (re)compiling the program.
.
.Sh AUTHORS
.An Randy Palamar Aq Mt randy@rnpnr.xyz
.
.Sh CAVEATS
Many of the newer dictionaries available online contain full json
data. This throws away the benefits of the original yomidict
format and requires a full json parser to handle. This is outside
the scope of this utility and will not be implemented. To check if
the dictionary is supported open a term_bank_XX.json file and check
for field names. If they are present the dictionary is not
supported.
